export { buttonDocPage } from './component-doc-data/buttonDoc'
export { formDocPage } from './component-doc-data/formDoc'
export { inputDocPage } from './component-doc-data/inputDoc'
export { modalDocPage } from './component-doc-data/modalDoc'
export { progressDocPage } from './component-doc-data/progressDoc'
export { tableDocPage } from './component-doc-data/tableDoc'
export { tabsDocPage } from './component-doc-data/tabsDoc'
